worlds:
    test 3:
    - T3XX07MQW
    new world:
    - 78XQNEBJ8
    - 53VAAGO0N
    - 071I56U59
    - 3QIOV6SPC
    - MBQY37ZAR
    - 54EN9WPZC
    - 1TGJMY9KW
    - C6WMLCUMA
    - AHHHVAVF7
    - C5S5W580B
    - SWEET9XQE
    - 040K89WZY
    - U0V76DGR8
